version: "3.8"
services:
  caddy:
    container_name: caddy
    image: caddy:2.6.4
    restart: unless-stopped
    networks:
      - caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
  authelia:
    container_name: authelia
    image: authelia/authelia:4.37.5
    restart: unless-stopped
    networks:
      - caddy
    expose:
      - 9091
    ports:
      - 9091:9091
    volumes:
      - ./authelia:/config
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis:7.0
    restart: unless-stopped
    networks:
      - caddy
networks:
  caddy:
    external: true
    name: caddy
