version: "2"
services:
  keycloak:
    platform: linux/amd64
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 8282:8080
    command:
      - "start-dev"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
  opa:
    platform: linux/amd64
    image: openpolicyagent/opa:latest
    ports:
      - 8383:8181
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "/policy/auth.rego"
    volumes:
      - ./policy:/policy
