version: "2"
services:
  keycloak:
    image: jboss/keycloak:latest
    ports:
      - 8282:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    volumes:
      - ./keycloak:/opt/jboss/keycloak/imports
    command: 
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
  opa:
    image: openpolicyagent/opa:latest
    ports:
      - 8383:8181
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "/policy/auth.rego"
    volumes:
      - ./policy:/policy
